### ISSUE TITLE
## Checklist

### ISSUE THREAD

**Issue by chill-otter** [leichain/crypto-coven-test#2]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Half no. Here's the version info from verbose mode:

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--fixup=warn', '--restrict-filenames', '--output', '%(upload_dat>
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e6a836d54
[debug] Python version 3.8.10 (CPython) - Linux-5.8.0-44-lowlatency-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
```
When running without --verbose, [youtube] Unable to decode n-parameter: … (No terminating paren } in {var b=a.split(""),…

However, fortunately, using `--verbose` works around the problem. :+1:
With `--verbose`, I get a few dozen lines of debug messages and then the download starts.
When running without `--verbose`, I see

```text
[youtube] 37gJCuf6UMY: Downloading webpage
[youtube] 37gJCuf6UMY: Downloading player 324f67b9
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (No terminating paren } in {var b=a.split(""),
c=[1070485609,7,function(d,e){d.push(e)},
```

and then the terminal is busy spewing lots more seemingly minified JS code, until I send SIGINT.

When I redirect stdout and stderr to a file (`… |& tee -- nparam.log`), it writes the first two lines and then seems stuck for about a minute, after which I gave up and sent SIGINT.

## Description

On Ubuntu focal, downloading from YouTube stopped, and instead, my terminal is flooded.
It worked fine a few hours ago.
Downloading from Twitch works as expected, so probably not a network problem.

Thanks for still maintaining compatible with ancient pythons!

__Originally posted by @mk-pmb in https://github.com/ytdl-org/youtube-dl/issues/31164__

**Comment by mk-pmb** [comment]
I'm surprised to see a full quote of my issue text here. Which license chain do you use for republishing it?
